import { Coach, Testimonial, FAQItem } from './types'

export const coaches: Coach[] = [
  {
    id: 'dodzi',
    name: 'Dodzi',
    role: 'Responsable Basket Club Saint Julien en Genevois',
    bio: 'Éducateur sportif et organisateur du Genevois Summer Camp, Dodzi est le moteur du camp depuis sa création. Son engagement pour la transmission et sa connaissance du territoire genevois font de lui le pilier de cette aventure.',
    diplomas: ['Éducateur Sportif'],
    citation: 'Mon objectif est simple : offrir aux jeunes du Genevois ce que je n\'ai pas eu à leur âge — un encadrement de qualité, près de chez eux.',
    image_url: '/images/coach-dodji.jpg',
    featured: true,
    order: 0,
  },
  {
    id: 'mike-alard',
    name: 'Mike Alard',
    role: 'Directeur technique Centre de formation Nanterre 92 (Pro A)',
    bio: 'Ancien entraîneur de Victor Wembanyama, Mike Alard est aujourd\'hui directeur du centre de formation de la JSF Nanterre 92, club de Pro A. Son expertise du haut niveau et sa capacité à faire progresser les jeunes talents en font la pierre angulaire du Genevois Summer Camp.',
    diplomas: ['DEJEPS'],
    citation: 'Ce qui fait la différence, ce n\'est pas le talent brut, c\'est la rigueur quotidienne et l\'envie d\'apprendre.',
    image_url: '/images/coach-mike.png',
    featured: true,
    order: 1,
  },
  {
    id: 'allan-perricaud',
    name: 'Allan Perricaud',
    role: 'Entraîneur individuel Paris',
    bio: 'Spécialiste du développement individuel, Allan Perricaud accompagne les joueurs dans l\'acquisition des fondamentaux techniques et la construction de leur palette offensive.',
    diplomas: ['DETB', 'BPJEPS'],
    citation: 'Chaque geste compte. La technique, c\'est ce qui te permet d\'exprimer ton talent dans les moments qui comptent.',
    image_url: '/images/coach-allan.jpg',
    featured: false,
    order: 2,
  },
  {
    id: 'baptiste-nivet',
    name: 'Baptiste Nivet',
    role: 'Entraîneur BCSJ',
    bio: 'Entraîneur au BCSJ, Baptiste Nivet allie compétences techniques et pédagogie pour permettre à chaque jeune de progresser à son rythme.',
    diplomas: ['DETB', 'BPJEPS'],
    citation: 'Le basket, c\'est d\'abord du plaisir. La progression vient naturellement quand on aime ce qu\'on fait.',
    image_url: '/images/coach-baptiste.jpg',
    featured: false,
    order: 3,
  },
  {
    id: 'jean-podevin',
    name: 'Jean Podevin',
    role: 'Entraîneur de sélection',
    bio: 'Fort d\'une expérience en sélection et en club, Jean Podevin apporte une vision tactique et collective du jeu, indispensable à la formation des jeunes joueurs.',
    diplomas: ['BPJEPS'],
    citation: 'Le collectif élève le niveau de chacun. Apprendre à jouer ensemble, c\'est apprendre à gagner ensemble.',
    image_url: '/images/coach-jean.jpg',
    featured: false,
    order: 4,
  },
  {
    id: 'clea-grandchamp',
    name: 'Cléa GRANDCHAMP',
    role: 'Coach Encadrement sportif',
    bio: 'Cléa Grandchamp apporte son dynamisme et sa passion du sport à l\'encadrement du Genevois Summer Camp. Son approche bienveillante et motivante aide chaque jeune à donner le meilleur de lui-même.',
    diplomas: ['BPJEPS'],
    citation: 'Le sport est une école de la vie. Transmettre, c\'est donner aux autres les clés pour se dépasser.',
    image_url: '/images/coach-cléa.jpg',
    featured: false,
    order: 5,
  },
  {
    id: 'thais-grandchamp',
    name: 'Thaïs GRANDCHAMP',
    role: 'Coach Encadrement sportif',
    bio: 'Thaïs Grandchamp complète l\'équipe d\'encadrement avec son énergie et son sens du collectif. Elle veille à ce que chaque participant trouve sa place et progresse dans une ambiance positive.',
    diplomas: ['BPJEPS'],
    citation: 'Ce qui compte, ce n\'est pas d\'être le meilleur, mais de donner le meilleur de soi-même.',
    image_url: '/images/coach-thaïs.jpg',
    featured: false,
    order: 6,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    author: 'Sophie M.',
    role: 'parent',
    content: 'Mon fils a passé une semaine incroyable. Il en parle encore tous les jours. L\'encadrement est exceptionnel et on sent une vraie passion chez les coachs.',
    rating: 5,
    created_at: '2025-07-10',
  },
  {
    id: '2',
    author: 'Lucas, 14 ans',
    role: 'jeune',
    content: 'Le meilleur camp de basket que j\'ai fait. Les coachs sont trop forts et j\'ai trop progressé. L\'heure avec le joueur pro, c\'était ouf !',
    rating: 5,
    created_at: '2025-07-12',
  },
  {
    id: '3',
    author: 'Karim B.',
    role: 'parent',
    content: 'Un cadre rassurant, des professionnels compétents, et des progrès visibles chez ma fille en une semaine. Je recommande les yeux fermés.',
    rating: 5,
    created_at: '2025-07-11',
  },
  {
    id: '4',
    author: 'Thomas, 13 ans',
    role: 'jeune',
    content: 'J\'ai rencontré des potes, j\'ai appris des moves, et en plus j\'ai vu mon idole en vrai. Vivement l\'année prochaine !',
    rating: 5,
    created_at: '2024-07-15',
  },
  {
    id: '5',
    author: 'Céline D.',
    role: 'parent',
    content: 'Un camp à taille humaine où chaque enfant est suivi individuellement. Le rapport qualité-prix est imbattable pour la région.',
    rating: 4,
    created_at: '2024-07-14',
  },
]

export const faqItems: FAQItem[] = [
  {
    id: '1',
    question: 'À partir de quel âge peut-on participer ?',
    answer: 'Le camp est ouvert aux jeunes de 11 à 16 ans (U11 à U16). Aucun niveau minimum n\'est requis, seulement l\'envie de jouer et de progresser.',
    order: 0,
  },
  {
    id: '2',
    question: 'Que faut-il apporter ?',
    answer: 'Pour le camp basket : tenue de sport, baskets (intérieur et extérieur), gourde, serviette, protège-dents (optionnel). Pour l\'internat : sac de couchage, affaires de toilette, vêtements pour la semaine.',
    order: 1,
  },
  {
    id: '3',
    question: 'Comment se déroule une journée type ?',
    answer: 'Accueil à 8h30, entraînement collectif à 9h, repas à 12h, technique individuelle à 14h, matchs à 16h, intervention d\'un joueur pro à 17h, fin à 18h.',
    order: 2,
  },
  {
    id: '4',
    question: 'Les repas sont-ils inclus ?',
    answer: 'En formule externat, le déjeuner est inclus. En formule internat, tous les repas (petit-déjeuner, déjeuner, dîner) sont inclus.',
    order: 3,
  },
  {
    id: '5',
    question: 'Quelle est la différence entre externat et internat ?',
    answer: 'L\'externat (300€/semaine) : le jeune rentre chaque soir chez lui. L\'internat (490€/semaine) : hébergement sur place et pension complète pour une immersion totale.',
    order: 4,
  },
  {
    id: '6',
    question: 'Faut-il un niveau minimum pour s\'inscrire ?',
    answer: 'Non, aucun niveau minimum n\'est requis. Les coachs adaptent les exercices au niveau de chaque participant. L\'essentiel est la motivation et l\'envie de progresser.',
    order: 5,
  },
  {
    id: '7',
    question: 'Comment se passe l\'encadrement en cas de problème ou d\'urgence ?',
    answer: 'L\'encadrement est assuré par des professionnels diplômés (DEJEPS, BPJEPS, BAFA). Une trousse de premiers secours est disponible en permanence et un protocole d\'urgence est établi avec les communes de Valleiry et Vulbens.',
    order: 6,
  },
  {
    id: '8',
    question: 'Peut-on s\'inscrire à la Multisport sans jouer au basket ?',
    answer: 'Absolument ! L\'édition Multisport est ouverte à tous, même aux jeunes qui ne jouent pas au basket. Les activités sont variées : foot en salle, VTT, tennis de table, sports collectifs.',
    order: 7,
  },
  {
    id: '9',
    question: 'Y a-t-il des filles dans le camp ?',
    answer: 'Oui, le camp est mixte et ouvert aux garçons comme aux filles de 11 à 16 ans.',
    order: 8,
  },
  {
    id: '10',
    question: 'Quels sont les moyens de paiement acceptés ?',
    answer: 'Le règlement s\'effectue par virement bancaire ou chèque. Un acompte peut être demandé à l\'inscription pour valider la place.',
    order: 9,
  },
  {
    id: '11',
    question: 'Comment se rendre au camp ?',
    answer: 'Le camp basket se déroule à Valleiry (74520), l\'édition Multisport à Vulbens (74520). Les deux communes sont situées à 20-30 minutes de Genève, accessibles en voiture ou en transport en commun.',
    order: 10,
  },
  {
    id: '12',
    question: 'Peut-on participer à une seule semaine ?',
    answer: 'Oui, chaque semaine est indépendante. Vous pouvez vous inscrire à l\'une ou l\'autre des sessions, ou aux deux.',
    order: 11,
  },
]

export const timelineSteps = [
  { time: '8h30', label: 'Accueil', icon: 'sun' },
  { time: '9h00', label: 'Entraînement collectif', icon: 'users' },
  { time: '12h00', label: 'Repas', icon: 'utensils' },
  { time: '14h00', label: 'Technique individuelle', icon: 'target' },
  { time: '16h00', label: 'Matchs', icon: 'trophy' },
  { time: '17h00', label: 'Intervention joueur pro', icon: 'star' },
  { time: '18h00', label: 'Fin de journée', icon: 'check' },
]
